### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bouweandela** [SciTools/python-stratify#54]
In order to use the support for dask arrays added in #52, a new release would be needed. Are there plans for creating a new release?

**Comment by bjlittle** [comment]
@bouweandela Good to hear from you, as always!

We need to show some major love to `python-stratify` in order to breath some life back into the CI et al, which has all gone majorly stale.

@HGWright is now going to be spinning up on `python-stratify` to do this work, and we aim to do a release as soon as possible. It'll also a learning exercise for him to understand the new code base, but ultimately he will be the core developer of `python-stratify`... so an ideal point-of-contact for you (apart for myself :wink:)

We have a [GH Project Board](https://github.com/orgs/SciTools/projects/17) to cover the forthcoming work, which we're about to refine and prioritize. We'll aim to deliver a Minimum Viable Product to unblock the release of `python-stratify` 0.3.0, then re-spin to mop up other outstanding tasks.

How this is okay with you?

**Comment by bouweandela** [comment]
The project board looks nice but also a lot of work. Are you planning to do everything on it before making the release? Maybe just reviving the test infrastructure and setting up automatic package upload to PyPI would be enough for a working release and the rest could go into a next release?

**Comment by bouweandela** [comment]
Great to hear that someone will be looking after this package! :partying_face:

**Comment by HGWright** [comment]
@bouweandela You will be pleased to hear, we are not planning to do everything on the board before the next release. Only the things that we thing are necessary will be included (Marked with the :key: MVP tag on the [board](https://github.com/orgs/SciTools/projects/17)). We currently estimate that at the very least we will have the next release out by the end of April. This date is not set in stone and if we can get it out for you sooner then we will.

One of the things we are planning to do in this release is to review the supported versions of Python and we have discussed only supporting Python 3.8 onwards. Would this be a problem for you?

**Comment by bouweandela** [comment]
>  Would this be a problem for you?

Not a problem at all, we're only supporting 3.8 and later in [ESMValTool](https://github.com/ESMValGroup/ESMValTool/)/[ESMValCore](https://github.com/ESMValGroup/ESMValCore/) too.

**Comment by HGWright** [comment]
@bouweandela Version 0.3.0 of Python-Stratify is now released and available on PYPI and Conda-Forge.  Please install, use and be sure to let us know if any issues come up.
